"""Removed Direction field from NavigationLogHistory

Revision ID: 498f6feb121f
Revises: 9b2930a87b4c
Create Date: 2025-07-29 15:43:56.366004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '498f6feb121f'
down_revision: Union[str, Sequence[str], None] = '9b2930a87b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('navigation_log_history', 'directions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('navigation_log_history', sa.Column('directions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
