"""add navigation log table

Revision ID: 5f0618d92029
Revises: 8c1419b7e66c
Create Date: 2025-07-29 13:15:16.814922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f0618d92029'
down_revision: Union[str, Sequence[str], None] = '8c1419b7e66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navigation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_place', sa.String(length=255), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_taken', sa.Interval(), nullable=True),
    sa.Column('directions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('navigation_logs')
    # ### end Alembic commands ###
