"""create geofences table

Revision ID: bdc2ffbe9f31
Revises: 498f6feb121f
Create Date: 2025-08-04 18:07:44.113153

"""
from typing import Sequence, Union
from geoalchemy2 import Geometry
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc2ffbe9f31'
down_revision: Union[str, Sequence[str], None] = '498f6feb121f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geofences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("DROP INDEX IF EXISTS idx_geofences_geom")
    op.create_index('idx_geofences_geom', 'geofences', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_geofences_geom', table_name='geofences', postgresql_using='gist')
    op.drop_table('geofences')
    # ### end Alembic commands ###
