import os
from dotenv import load_dotenv

load_dotenv()

AUTHORIZATION_KEY = os.getenv("AUTHORIZATION_KEY")
DATABASE_URL = os.getenv("DATABASE_URL")
MONGO_URL = os.getenv("MONGO_URL")
print(MONGO_URL)
SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")
SMTP_USERNAME = os.getenv("SMTP_USERNAME")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
SMTP_FROM = os.getenv("SMTP_FROM")
SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = int(os.getenv("SMTP_PORT", 465))
SMTP_TLS = os.getenv("SMTP_TLS") == "True"
MAX_DISTANCE_KM = 400
VALHALLA_BASE_URL = os.getenv("VALHALLA_BASE_URL")
TILESERVER_URL = os.getenv("TILESERVER_URL")
WEATHER_SERVICE_URL = os.getenv("WEATHER_SERVICE_URL")
WEATHER_API_KEY = os.getenv("WEATHER_API_KEY")
NOMINATIM_URL = os.getenv("NOMINATIM_URL")
NOMINATIM_REVERSE_URL = os.getenv("NOMINATIM_REVERSE_URL")
PHOTON_URL = os.getenv("PHOTON_URL")
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24